version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --unsafe-perm -g @angular/cli@8.3.3
      - npm install
  build:
    commands:
      - ./bin/pre_build.sh
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync dist/ s3://$DEPLOY_BUCKET --delete
      - zip -rq web.zip *
artifacts:
  files:
    - web.zip
