version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - aws s3 rm s3://$DEPLOY_BUCKET --recursive
  post_build:
    commands:
      - touch web_destroy.fin
artifacts:
  files:
    - web_destroy.fin
