version: '3'
services:
  angular:
    build: ./angular
    tty: true
    ports:
      - 4200:4200
    environment:
      API_BASE_URL: 'mock-server'
    volumes:
      - ../:/src/
    networks:
      - frontend
  shellcheck:
    image: koalaman/shellcheck-alpine
    tty: true
    volumes:
      - ../bin/:/scripts/
      - ./shellcheck/bin/shellcheck.sh:/shellcheck.sh
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
